# External data keywords
external_data_keywords:
  npk: Majemuk
  urea: Urea
  fosfat: Fosfat
  phospate: Fosfat
  za : ZA
  zk : ZK
  0-0-: Kalium
  nitr: Nitrogen
  ganik: Organik
  kompos: Organik

# Data path
catalog_data_path: data/raw/Product Catalog.xlsx
catalog_data_sheet: Product Catalog
catalog_data_processed_path: data/processed/Product Catalog.csv

pos_data_path: data/raw/Product Name from PoS Transactions.xlsx
pos_data_sheet: Product Name
pos_data_processed_path: data/processed/Product Name from PoS Transactions.csv

external_data_path: data/raw/Produk_Pertanian_Brand_Katalog.csv
external_data_processed_path: data/processed/Produk_Pertanian_Brand_Katalog.csv